apple login 관련 충돌 해결
wooda-ege/lovebird-ios pull request #10
Opened 2023-11-09 06:49 UTC by yeeton37

2023-11-09 11:45 UTC, ghkdemrdus requested changes

2023-11-09 11:45 UTC, ghkdemrdus commented on LoveBird/Sources/Network/APIClient.swift
> +        // MARK: - Multiparts
파라미터 넘겨주는걸 저렇게 관리하는 거 보다 Encodable 상속받는 함수 만들어줘서 관리하는데 훨씬 편해!
필드를 추가하거나 삭제하거나 변수명 바꾸기가 편해져~

`return .requestJSONEncodable(encodable)` 에 들어갈 수 있게 리팩토링 한번 해봐!

2023-11-09 11:45 UTC, ghkdemrdus commented on LoveBird/Sources/Root/RootCore.swift
> +          var rootState: State
[nit] 이건 if 조건문에서 rootState 값이 확정이 된다면 기존에 사용하던 let을 쓰는 걸 추천!

2023-11-09 12:39 UTC, yeeton37 commented on LoveBird/Sources/Network/APIClient.swift
> +        // MARK: - Multiparts
[984a6e2](https://github.com/wooda-ege/lovebird-ios/pull/10/commits/984a6e212f046f98d15016b306d45eb6601ee838) 수정했습니닷!

2023-11-09 12:40 UTC, yeeton37 commented on LoveBird/Sources/Root/RootCore.swift
> +          var rootState: State
아하 ㅋㅋㅋ이해했오!
[249ebe9](https://github.com/wooda-ege/lovebird-ios/pull/10/commits/249ebe98da9cc7f35d0301548c241be4d170f0a0)

2023-11-09 12:46 UTC, ghkdemrdus commented on LoveBird/Sources/Network/APIClient.swift
> +        // MARK: - Multiparts
TokenInfo 말고 기존에 사용하던 AuthRequest랑 필드가 같아서 그거 써도 될거같아!

2023-11-12 05:53 UTC, yeeton37 commented on LoveBird/Sources/Network/APIClient.swift
> +        // MARK: - Multiparts
[ff8b1c2](https://github.com/wooda-ege/lovebird-ios/pull/10/commits/ff8b1c252e005e819412954322e9bed51e6fe9f7) 오 그러네! 다시 수정했어 예리하십니다

2023-11-12 06:03 UTC, ghkdemrdus approved these changes

2023-11-12 06:03 UTC, merged