[Feat] SearchPlaceView 관련 네트워크 모델 추가 및 R.Swift 적용
wooda-ege/lovebird-ios pull request #2
Opened 2023-06-23 12:07 UTC by yeeton37

- SearchPlaceView 관련 네트워크 모델 추가 (PlaceRequest, SearchPlaceResponse)
- R.Swift 적용
- 장소 이름 입력시 뜨는 리스트뷰 수정
- 인덴트 2로 마저 수정

++ 네트워크 API 구조 수정 필요 ( 수정 이후에 로직 변경 필요)

2023-06-23 13:13 UTC, ghkdemrdus requested changes
PR 리뷰 반영할 때 해야할 것

1. 불필요한 코드 제거
2. String 및 Image R.swift 사용
3. Commit에 필요없는 파일 제거

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Resources/Assets.xcassets/Images/back.imageset/Contents.json
> +}
우리가 Asset Image 네이밍을 `ic_xxx` 으로 하기로 했으니 ic_back으로 바꾸면 될거같아!
그리고 image(예를 들면 splash ImageView) 같은 경우에는 `img_xxx` 으로 지을거 같으니 네이밍 수정해줘!
map과 photo도 마찬가지야!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Resources/Assets.xcassets/Images/flower.imageset/Contents.json
> +}
이 친구는 예시 사진이니깐 Commit 할 때는 빼고 해주면 돼!
Commit 내용은 꼭 들어가는 것만 하면 되구 예를들어

1. 임시 주석(TODO 등을 제외한 본인의 생각을 적거나 그런 주석)
2. 임시 코드 (print 라던지 프로덕트에 필요없는 코드)
3. 사용되지 않는 파일 (해당 flower.asset)

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +
저번에 말한거처럼 어떤 용도의 버튼인지 CustomButton -> DiarySelectPlaceButton 등으로 변경해주면 좋아!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +        }
Swiftlint를 사용하면 해결될거 같긴한데
```swift
.frame(
  width: 15,
  height: 15
)
```
이렇게 ) 를 개행해주면 될거 같아!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +      self.presentationMode.wrappedValue.dismiss()
위에서 말했듯 Print같은거는 최대한 빼주는게 좋아!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +      print("뒤로가기 버튼 눌렸습니동")
여기도 마찬가지!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +        .frame(width: 10, height: 15)
실제로 사용되는 크기는 17 22로 보이는데 다시 확인 부탁할게!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/ImagePicker.swift
> +            .foregroundColor(Color(uiColor: .secondarySystemBackground))
우리가 정의한 Color를 사용하는게 좋아보임!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/ImagePicker.swift
> +  @Binding var image: Image?
Image에 관한 Property가 왜 두개여야하는지 설명해줘!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Extension/UIColor+Extension.swift
> +  }
R.Swift를 사용할거니 해당 파일은 삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Model/KakaoMap.swift
> +//  }
사용하지 않는 파일 삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Network/APIClient.swift
> +    let url = URL(string: Place.baseURL + endpoint.path)!
디스코드에 올린 Config.swift 받아서 해당 위치에 넣고 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Network/NetworkManager.swift
> +    }
사용하지 않는 파일 삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Network/SearchPlaceAPI.swift
> +        request.setValue("KakaoAK e2b463ff0435646fe4d1b4213c6527b1", forHTTPHeaderField: "Authorization")
해당 정보는 유출되면 안되는 정보이니 Config.swift에 선언하고 사용!
Github가 public이라서 혹시 모를일을 조심해줘야해!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Network/SearchPlaceAPI.swift
> +    static let path = "/v2/local/search/keyword.json"
이부분도 필요한 내용은 Config.swift에 빼주기!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +              height: 15)
개행 필요!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +          Image("map")
Image(R.image.ic_map) 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +      Image("back")
Image(R.image.ic_back) 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +          Image("map")
Image(R.image.ic_map) 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +      Image("back")
Image(R.image.ic_back) 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +      print("뒤로가기 버튼 눌렸습니동")
print 빼기!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +      print("완료 버튼 눌렀습니동")
print 빼기!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +    Button("완료") {
common_complete = "완료";
와 같은 localizable 추가해서 사용하기!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryCore.swift
> +  enum DiaryCoreAction: Equatable {
DiaryCoreAction -> Action

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryCore.swift
> +    var place: String = "장소 선택"
장소 선택도 localizable 추가!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +          .background(Color(uiColor: .secondarySystemBackground))
Color Asset 지정해서 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +            place = "장소 선택"
localizable 추가 및 개행 수정!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +              place == "장소 선택" ? CustomButton(title: place)
마찬가지로 Localizable!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +            }
Padding 중복 제거

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +                .foregroundColor(.gray)
Color Asset 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +              .colorMultiply(Color(uiColor: .secondarySystemBackground))
Color Asset 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +              .frame(height: 342)
TextEditor 높이가 342고정이 맞는지 다시 체크!
저번에 얘기한걸로 기억하길 키보드 높이와 핸드폰 높이를 고려해서 계산한 값을 넣기로 했음!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +                .foregroundColor(.gray)
Color Asset!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +          ImagePickerView(image: $image)
image는 State말고 따로 @State 를 만들어준 이유가 있어?

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +        UIEdgeInsets(top: 10, left: 5, bottom: 5, right: 5)
한줄로 써도 될듯!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/Extension+UIApplication.swift
> +}
indent 2로 수정!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/ImagePicker.swift
> +  func makeUIViewController(context: Context) -> some UIViewController {
이 파일 두 개인거 같은데 해당 파일 삭제해할듯!
Soucres/Componenets/ImagePicker.swift 만 있어도 될듯!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/NetworkManager.swift
> +                return data
얘도 삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceAPI.swift
> +
삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceCore.swift
> +        return .none
여기 있는 return .none 다 삭제! 아래 포함!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +//  @State private var searchTerm = ""
주석 삭제!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +          .background(Color(uiColor: .secondarySystemBackground))
Color Asset 사용!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceCore.swift
> +  enum SearchPlaceAction: Equatable {
Action으로 네이밍 수정!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +    static let placeholder = " 장소, 주소를 입력해주세요."
Localizable 추가!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +//  @Binding var placeSelection: String
주석 제거!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +          .padding(.bottom, 10)
.padding([.top, .bottom], 10) 으로 수정!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +          .navigationTitle("장소 선택")
Localizable!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +      //      .scrollContentBackground(.hidden)
주석 제거!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/SearchPlaceView.swift
> +      }
요것도 안쓸거니깐 제거!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Place/SearchPlaceView.swift
> +  @Binding var placeSelection: String
이것도 View의 State에 추가!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Place/SearchPlaceView.swift
> +    static var placeholder = " 장소, 주소를 입력해주세요."
Localizable!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Place/SearchPlaceView.swift
> +          .padding(.bottom, 10)
.padding([.top, .bottom], 10) 으로 수정!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Place/SearchPlaceView.swift
> +          .background(Color(uiColor: .secondarySystemBackground))
Color Asset!

2023-06-23 13:13 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Place/SearchPlaceCore.swift
> +
해당 파일도 두개인거 같은데 확인!

2023-06-23 13:19 UTC, ghkdemrdus requested changes
PR 리뷰 반영할 때 해야할 것

1. 불필요한 코드 제거
2. String 및 Image R.swift 사용
3. Commit에 필요없는 파일 제거

2023-06-23 13:29 UTC, yeeton37 commented on LoveBird/Resources/Assets.xcassets/Images/flower.imageset/Contents.json
> +}
헉 처음 알았당

2023-06-23 13:30 UTC, yeeton37 commented on LoveBird/Resources/Assets.xcassets/Images/back.imageset/Contents.json
> +}
굿! 수정 완료한 거만 👀 이모티콘 달아놓을게유

2023-06-23 13:35 UTC, yeeton37 commented on LoveBird/Sources/Components/CustomButton.swift
> +        .frame(width: 10, height: 15)
이거 한번 얘기해봐야할 것같아!!

17,22로 했더니 실제 화면에서 너무 크게 보이더라고 ㅠ

<img width="355" alt="스크린샷 2023-06-23 오후 10 34 58" src="https://github.com/wooda-ege/lovebird-ios/assets/98514397/8fbc2c30-53fe-4d1c-af3d-c1ea622ef6e0">

2023-06-23 13:37 UTC, yeeton37 commented on LoveBird/Sources/Components/ImagePicker.swift
> +            .foregroundColor(Color(uiColor: .secondarySystemBackground))
(아직 해결 안됨)

2023-06-23 13:48 UTC, yeeton37 commented on LoveBird/Sources/Extension/UIColor+Extension.swift
> +  }
ImagePickerView에서 이미지가 선택되면 그걸 가지고 있는 변수인 selectedUIImage, 선택 한뒤 이전 화면으로 다시 돌아왔을 때 이미지를 보여주는 image 두개로 나눴어!

혹시 다른방법이 있을까유?

2023-06-23 13:49 UTC, yeeton37 commented on LoveBird/Sources/Network/APIClient.swift
> +    let url = URL(string: Place.baseURL + endpoint.path)!
Config는 해당 위치에 넣었어!
근데 그부분 baseURL이 고정돼있길래 따로 Place.swift 만들어서 따로 테스트 해봤어!!

2023-06-23 13:51 UTC, yeeton37 commented on LoveBird/Sources/Network/NetworkManager.swift
> +    }
<img width="390" alt="스크린샷 2023-06-23 오후 10 50 41" src="https://github.com/wooda-ege/lovebird-ios/assets/98514397/23d47258-1555-4e29-af91-9607d94798fd">


흠 여기에선 삭제해줬는데 또 뜨나..? 어디에 남아있는거지

2023-06-23 13:55 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +    Button("완료") {
String 타입이라 어떻게 하시는지 아십니까...

2023-06-23 13:57 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/DiaryCore.swift
> +    var place: String = "장소 선택"
위와 마찬가지로 String인데 가능한지 궁금.!!

2023-06-23 13:59 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +              .frame(height: 342)
맞아맞아 수정필요!!

2023-06-23 14:01 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/Extension+UIApplication.swift
> +}
<img width="550" alt="스크린샷 2023-06-23 오후 11 01 09" src="https://github.com/wooda-ege/lovebird-ios/assets/98514397/6fd55ec2-cc15-4720-9a88-1973e2966c7e">

내꺼에는 다 수정 돼있는데 왜 다르지..?

2023-06-23 14:02 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/ImagePicker.swift
> +  func makeUIViewController(context: Context) -> some UIViewController {
내꺼엔 이파일이 아예 안뜨는디 얘기해봐야할듯!

2023-06-24 15:00 UTC, ghkdemrdus commented on LoveBird/Sources/Components/CustomButton.swift
> +        .frame(width: 10, height: 15)
이런건 공유해주면 될듯!

2023-06-24 15:01 UTC, ghkdemrdus commented on LoveBird/Sources/Network/APIClient.swift
> +    let url = URL(string: Place.baseURL + endpoint.path)!
Place.baseURL -> Config.kakaoMapURL 이런식으로 바꾸는게 좋을듯!

2023-06-24 15:02 UTC, ghkdemrdus commented on LoveBird/Sources/Network/NetworkManager.swift
> +    }
Finder에서 직접 찾아서 삭제해주면 될듯!

2023-06-24 15:05 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +    Button("완료") {
R.String.localizable.xxx 였던거 같아!
내가 사용하는 코드 한번 찾아보면 도움이 될거야!

2023-06-24 15:05 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +              .frame(height: 342)
foreground color 중복도 제거!

2023-06-24 15:05 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/Extension+UIApplication.swift
> +}
아 중복 파일인가봐 그럼 제거하면 될듯!

2023-06-26 00:10 UTC, yeeton37 commented on LoveBird/Sources/Components/ImagePicker.swift
> +  @Binding var image: Image?
ImagePickerView에서 이미지가 선택되면 그걸 가지고 있는 변수인 selectedUIImage, 선택 한뒤 이전 화면으로 다시 돌아왔을 때 이미지를 보여주는 image 두개로 나눴어!

혹시 다른방법이 있을까유?

2023-06-26 00:17 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/ImagePicker.swift
> +  func makeUIViewController(context: Context) -> some UIViewController {
해결!!

2023-06-26 00:17 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/Extension+UIApplication.swift
> +}
해결!

2023-06-27 00:57 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/CustomButton.swift
> +    Button("완료") {
StringProtocol이라 String(resource:)로 묶어주니 해결됐당! ㅎ

2023-06-27 14:36 UTC, yeeton37 commented on LoveBird/Sources/Root/Place/SearchPlaceView.swift
> +  @Binding var placeSelection: String
삭제!

2023-06-29 12:32 UTC, ghkdemrdus approved these changes
아주 잘했어 👍👍
앞으로도 코드하나하나 짤때 신경쓰면 실력이 많이 늘거야!
약간 만 더 수정하고 Squash 머지하면 될듯!

2023-06-29 12:32 UTC, ghkdemrdus commented on LoveBird/Resources/Assets.xcassets/Images/ic_flower.imageset/Contents.json
>      {
요거는 예시 이미지라 빼는거 아니였는가..!

2023-06-29 12:32 UTC, ghkdemrdus commented on LoveBird/Sources/Components/DiarySelectPlaceButton.swift
> +        )
``` swift
.frame(
  width: .infinity,
  height: 44
  alignment: .leading
)
```
이렇게 하면 좋을거 같군!

2023-06-29 12:32 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +          .padding([.leading, .trailing], 16)
요거 알고보니 padding(.horizontal, 16) 도 있드라구 ㅋㅋㅋ

2023-06-29 12:40 UTC, yeeton37 commented on LoveBird/Resources/Assets.xcassets/Images/ic_flower.imageset/Contents.json
>      {
엇 뺐는데 다시 들어갔나봐..! 수정수정!

2023-06-29 12:41 UTC, yeeton37 commented on LoveBird/Sources/Root/Diary/DiaryView.swift
> +          .padding([.leading, .trailing], 16)
헐랭....개꿀팁...

2023-06-29 12:57 UTC, yeeton37 commented
- 불필요한 코드 제거
- String 및 Image의 R.Swift 적용
- 중복되는 파일 제거 (reference에 잡히지 않은 파일이 있어서 두 개인 파일 확인 후 제거)
- @State, @Binding 제거

2023-06-29 12:57 UTC, merged