로그인 관련 로직 수정
wooda-ege/lovebird-ios pull request #7
Opened 2023-09-24 09:21 UTC by yeeton37

애플로그인 버튼 및 로직 수정
로그인 DTO 수정

2023-09-24 09:48 UTC, ghkdemrdus requested changes
keyChain을 사용하니 UserData에서 Token관련 값들도 다 빼면 좋을거 같아!

2023-09-24 09:48 UTC, ghkdemrdus commented on LoveBird/Sources/Model/WebApi.swift
> +    return true
요거 파라미터 상관없이 true를 리턴하는데 수정할 예정이면 // TODO 를 명시해놔!

2023-09-24 09:48 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Home/HomeCore.swift
>        title: profile.nextAnniversary?.kind.description ?? ""
오 굿굿! 아래도 profile.nextAnniversary -> nextAnniversary로 수정하면 좋을듯!

2023-09-24 09:48 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/LoginView.swift
> +                  .frame(width: 343, height: 60)
보통 대부분 회사에서 좌우로 거의 꽉찬 뷰인 경우, Frame Width는 절대값을 명시하기 보단 좌우 Padding을 주는 식으로 구현해! 

+) indent 도 맞추면 좋고

2023-09-24 09:48 UTC, ghkdemrdus commented on LoveBird/Sources/Network/Request/AuthRequest.swift
> +  let provider: String
Provider는 Enum으로 명시해주는게 좋아!

2023-09-24 09:48 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/Keychain.swift
> +enum KeychainError: Error {
Keychain로직은 어디 참고에서 구현한겨? 궁금..

2023-09-24 10:11 UTC, yeeton37 commented on LoveBird/Sources/Root/Login/Keychain.swift
> +enum KeychainError: Error {
> Keychain로직은 어디 참고에서 구현한겨? 궁금..

https://www.kodeco.com/4875322-sign-in-with-apple-using-swiftui 여기꺼 보고 고대로 따라했는데 되는지는 해봐야할듯 후후,,,

2023-09-24 10:20 UTC, yeeton37 commented
리뷰 반영해서 수정했숩니당!!

2023-09-24 10:21 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/Keychain.swift
> +enum KeychainError: Error {
아하 ㅋㅋㅋ 사용하는건 상관없고 너무 좋은데 왜 사용하는지만 공부해보면 좋아! 
KeyChain vs UserDefaultKeys 로 비교해보고, 내부 로직도 어떻게 동작하는건지 한번 파악해보면 좋아!

2023-09-24 16:04 UTC, ghkdemrdus approved these changes
이거 해결만 하고 바로 머지해!

2023-09-24 16:04 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/LoginView.swift
>                    .onTapGesture(perform: showAppleLogin)
요거 Indent도!

2023-09-24 16:04 UTC, ghkdemrdus commented on LoveBird/Sources/Network/Request/AuthRequest.swift
> +enum Provider: Encodable {
``` swift
enum SNSProvider: String, Encodable {
  case apple = "APPLE"
  case kakao = "KAKAO"
}
```
Provider의 목적을 좀더 명확하게 해주고, case는 보통 lowercase이니 이렇게 수정하는걸 추천!

2023-09-24 16:04 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Home/HomeCore.swift
> +      with: nextAnniversary.anniversaryDate ,
반점 앞에 스페이스 제거!
with: nextAnniversary.anniversaryDate ,
->
with: nextAnniversary.anniversaryDate,

2023-09-26 11:02 UTC, yeeton37 commented
수정완료했습니다!

2023-09-26 11:53 UTC, ghkdemrdus requested changes

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/LoginCore.swift
> +          userData.store(key: .idToken, value: tokenString)
idToken이랑 provider 저장하는 이유를 알 수 있을까?

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/RootCore.swift
> +//          userData.remove(key: .accessToken)
사용안하는거는 main에 머지할때 제거하기

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/RootCore.swift
> +//          rootState = .onboarding(OnboardingCore.State())
마찬가지로 제거하기

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Info.plist
> -	<key>NSPhotoLibraryUsageDescription</key>
요 권한이 없어진 이유가 있어?

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/LoginCore.swift
> +        userData.store(key: .provider, value: provider)
이 두개를 저장해주는 이유가 있어?

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Login/LoginView.swift
> +                      viewStore.send(.kakaoLoginTapped(Provider.KAKAO.rawValue, idToken))
보통 파라미터로 값을 넘길때 enum같은 경우는 그자체로 넘기고, 받은 곳에서 필요시 rawValue로 빼는게 좋아!

2023-09-26 11:53 UTC, ghkdemrdus commented on LoveBird/Sources/Root/RootCore.swift
> +            await send(.updateRootState(.coupleLink(CoupleLinkCore.State())))
catch는 로직 안에 다른게 들어가있어!

2023-09-29 13:05 UTC, yeeton37 commented on LoveBird/Sources/Root/Login/LoginCore.swift
> +          userData.store(key: .idToken, value: tokenString)
로그인하고 받은 토큰과 provider를 나중에 프로필 등록할 때 서버에 전달해줘야해서 어디에 저장해놓을지 고민하다가 user랑 관련있는 값이라고 생각해서 userData에 저장했숨당!
그치만 userDefaults로 저장하기에는 일회성으로 필요한 것이라고 생각돼서 파라미터로 넘겨주는거로 수정할게욥!

2023-09-29 13:13 UTC, yeeton37 commented on LoveBird/Info.plist
> -	<key>NSPhotoLibraryUsageDescription</key>
음?? 안없앴는데 엑코에는 있따고 뜨는데 뭐지,,,
<img width="737" alt="스크린샷 2023-09-29 오후 10 12 35" src="https://github.com/wooda-ege/lovebird-ios/assets/98514397/2f489dd3-ff19-4115-bbd1-effab2142d3e">

2023-09-29 13:13 UTC, yeeton37 commented on LoveBird/Sources/Root/Login/LoginView.swift
> +                      viewStore.send(.kakaoLoginTapped(Provider.KAKAO.rawValue, idToken))
오오 처음 알았다..!꿀팁!!!

2023-09-29 13:13 UTC, yeeton37 commented on LoveBird/Sources/Root/RootCore.swift
> +            await send(.updateRootState(.coupleLink(CoupleLinkCore.State())))
헉 똑같은걸 넣어버렸네유

2023-10-25 09:55 UTC, ghkdemrdus commented on LoveBird/Sources/Root/Onboarding/OnboardingTextFieldState.swift
> +import SwiftUI
OnboardingTextFieldState -> TextFieldState로 통합했는데 확인해줄수있어?
내가 Merge Conflict 해결할때 바꿨는데 오류가 생긴거야?

2023-10-25 14:15 UTC, ghkdemrdus approved these changes

2023-11-08 06:57 UTC, merged